# **Padhai - OneFourthLabs - Data Science (Numpy)**

In [2]:
import numpy as np

## Exercise 1 : Area of circle/sphere quarter in a square/cube

In [46]:
N = 10000000

### 1a : Area of the quarter circle 2D

In [25]:
array_one = np.random.rand(N,2)
print(array_one)

[[0.73387767 0.12065259]
 [0.71157136 0.50364109]
 [0.98629319 0.04128055]
 ...
 [0.91608723 0.54563709]
 [0.0734719  0.95867997]
 [0.4522668  0.77910878]]


In [26]:
hypotenuse = lambda base,height : (base**2 + height**2)**0.5

In [27]:
#test if the function is working
print(hypotenuse(3,4))

5.0


In [28]:
%%time
dist_map = np.array(list(map(hypotenuse, array_one[:,0],array_one[:,1])))
print(dist_map)

[0.74372944 0.87177299 0.9871567  ... 1.06627184 0.96149124 0.90086389]
CPU times: user 14.1 s, sys: 404 ms, total: 14.5 s
Wall time: 14.5 s


In [29]:
ratio = (dist_map[dist_map <= 1].size)/N
print(ratio)

0.7853554


### 1b : Area of a quarter sphere 3D

In [30]:
array_two = np.random.rand(N,3)
print(array_two)

[[0.01239078 0.98094616 0.84217801]
 [0.43257248 0.17660892 0.13444267]
 [0.86442578 0.80422133 0.16210604]
 ...
 [0.75763226 0.39927326 0.84477497]
 [0.99894587 0.7336454  0.20949138]
 [0.05629238 0.06639266 0.1300187 ]]


In [31]:
distance_3d = lambda x,y,z : ( x**2 + y**2 + z**2 )**0.5 

In [32]:
dist_map_3d = np.array(list(map(distance_3d, array_two[:,0],array_two[:,1],array_two[:,2])))

In [33]:
ratio_3d = (dist_map_3d[dist_map_3d <= 1].size)/N
print(ratio_3d)

0.5237324


###1c : achieve the above in one single function line

In [47]:
def area_outside_circle(npoints, ndim):
    points = np.random.rand(npoints, ndim)
    return np.sum(np.sum(points * points, axis = 1) > 1)/npoints

In [52]:
%%time
area_outside_circle(N,10)

CPU times: user 135 ms, sys: 4.97 ms, total: 140 ms
Wall time: 143 ms


0.99756

##Exercise 2 : Questions regarding cricket dataset

In [63]:
!cd drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Numpy/Dataset_files && ls

cric_data-200320-181217.tsv  planets_small.txt	planets.txt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!cat drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Numpy/Dataset_files/cric_data-200320-181217.tsv

In [65]:
Cricket_data = np.loadtxt('drive/MyDrive/Colab_Notebooks/OneFourthLabs_Padhai/Numpy/Dataset_files/cric_data-200320-181217.tsv',delimiter = '\t',skiprows = 1, usecols=(1,2,3))

### Question a : Calculate the Mean, Median, IQR for Sachin, Rahul, India

In [66]:
mean_array = np.mean(Cricket_data, axis =0)
median_array = np.median(Cricket_data, axis =0)
Quartiles = np.percentile(Cricket_data, axis =0, q=(25,50,75) )
IQR = Quartiles[2,:] - Quartiles[0,:]

In [67]:
print(mean_array)
print(median_array)
print(IQR)

[ 39.87555556  32.06222222 220.79555556]
[ 27.  22. 216.]
[57. 46. 98.]


### Question b : Create a histogram for Sachin's scores with 10 bins

In [68]:
Sachin_histogram = np.histogram(a=Cricket_data[:,0] ,bins = 10)

In [69]:
Sachin_histogram

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

### Question c : Find mean of Sachin's score per every 25 matches

In [70]:
Sachin_scores = Cricket_data[:,0]
Sachin_scores_reshaped = Sachin_scores.reshape(25,9)
Sachin_mean_by_25 = np.mean(Sachin_scores_reshaped,axis = 0)

In [71]:
print(Sachin_mean_by_25)

[37.04 45.44 40.24 44.76 51.32 28.52 37.88 32.28 41.4 ]


### Question d : Take mean of Sachin's scores where he scored a century

In [72]:
Sachin_century_scores = Sachin_scores[Sachin_scores >= 100]
Sachin_century_mean = np.mean(Sachin_century_scores)
print(Sachin_century_mean)

125.0


### Question e : Find mean of Sachin's scores where rahul scored less than 10

In [73]:
Rahul_less_than_10 = Cricket_data[Cricket_data[:,1] < 10]
Sachin_mean_when_rahul_10 = np.mean(Rahul_less_than_10[:,0])
print(Sachin_mean_when_rahul_10)

40.74285714285714


### Question f : Find mean of sachin's score based india's quartile scores

In [74]:
print(Quartiles)
print(Quartiles[0,2])

[[  6.   7. 175.]
 [ 27.  22. 216.]
 [ 63.  53. 273.]]
175.0


In [75]:
India_q1 = Cricket_data[ ( Cricket_data[:,2] < Quartiles[0,2] ) ]
Sachin_India_q1 = India_q1[:,0]
Sachin_india_q1_mean = np.mean(Sachin_India_q1)

In [76]:
Sachin_india_q1_mean #Sachin mean when india scores in Q1

19.672727272727272

In [77]:
India_q2 = Cricket_data[ ( Cricket_data[:,2] >= Quartiles[0,2]) & ( Cricket_data[:,2] < Quartiles[1,2] ) ]
Sachin_India_q2 = India_q2[:,0]
Sachin_india_q2_mean = np.mean(Sachin_India_q2)

In [78]:
Sachin_india_q2_mean #Sachin mean when india scores in Q2

36.535714285714285

In [79]:
India_q3 = Cricket_data[ ( Cricket_data[:,2] >= Quartiles[1,2]) & ( Cricket_data[:,2] < Quartiles[2,2] ) ]
Sachin_India_q3 = India_q3[:,0]
Sachin_india_q3_mean = np.mean(Sachin_India_q3)

In [80]:
Sachin_india_q3_mean #Sachin mean when india scores in Q3

38.642857142857146

In [81]:
India_q4 = Cricket_data[ ( Cricket_data[:,2] >= Quartiles[2,2]) ]
Sachin_India_q4 = India_q4[:,0]
Sachin_india_q4_mean = np.mean(Sachin_India_q4)

In [82]:
Sachin_india_q4_mean

63.44827586206897

### Question g : For every match find out who scored more(Sachin or Rahul)

In [83]:
Who_scored_more_bool = Cricket_data[:,0] > Cricket_data[:,1]

In [84]:
Cricket_data [Who_scored_more_bool],

(array([[100.,  78., 342.],
        [ 71.,  24., 307.],
        [104.,  17., 229.],
        [ 86.,  74., 288.],
        [ 85.,  12., 224.],
        [ 37.,   4., 297.],
        [ 14.,   5., 139.],
        [ 62.,   0., 134.],
        [138.,  39., 299.],
        [ 38.,   9., 242.],
        [ 46.,  14., 152.],
        [ 65.,   0., 104.],
        [ 39.,  26., 155.],
        [ 48.,   4., 168.],
        [141.,  48., 282.],
        [ 62.,   7., 228.],
        [ 41.,  32., 255.],
        [186., 153., 345.],
        [ 27.,   1., 292.],
        [ 27.,   6., 299.],
        [ 51.,   3., 233.],
        [ 18.,   1., 332.],
        [146.,  30., 264.],
        [141.,  36., 306.],
        [ 65.,   0., 141.],
        [ 28.,   0., 124.],
        [123.,  19., 305.],
        [120.,  13., 273.],
        [ 81.,  43., 274.],
        [ 54.,   5., 256.],
        [122.,  15., 227.],
        [  4.,   0., 157.],
        [ 14.,   5., 353.],
        [100.,   4., 211.],
        [ 57.,   7., 499.],
        [ 99.,  74.,

In [85]:
#Cricket_data [~Who_scored_more_bool]
who_scored_more = np.where( Who_scored_more_bool == True , 'Sachin','Rahul')

In [86]:
who_scored_more

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Sachin', '

### Question h : How many more runs does Sachin score on an average after scoring x runs

In [87]:
x = 5 #lets say he has already scored x runs
Sachin_score_after_x = Sachin_scores[Sachin_scores >= x] - x
Sachin_score_after_x_mean = np.mean(Sachin_score_after_x)

In [88]:
Sachin_score_after_x_mean

45.61363636363637

### Question i : How many matches did Sachin take to score 1000 runs, 2000 runs and so on

In [ ]:
sachin_cumsum = np.cumsum(Sachin_scores)
print(sachin_cumsum)

In [90]:
Sachin_histogram_bin_1000 = np.histogram (sachin_cumsum, range = (0,10000))
print(Sachin_histogram_bin_1000)

(array([29, 18, 26, 25, 26, 26, 23, 22, 30,  0]), array([    0.,  1000.,  2000.,  3000.,  4000.,  5000.,  6000.,  7000.,
        8000.,  9000., 10000.]))


In [91]:
def add(num1, num2):
  return num1+num

##Practice

In [92]:
np.array(["Abhijit","aadi","manav"])

array(['Abhijit', 'aadi', 'manav'], dtype='<U7')